package mmm;

/**
 * This class is designed to specify the property values to load for our
 * language files when loading up the app and supports the use of other
 * translations int he development of this application.
 *
 * @author Stanley Lim
 * @version 0.1
 */
public enum MetroLanguageProperty {
    /* GENERIC STATEMENTS */
    BUTTON_OK,
    BUTTON_CANCEL,

    /* WELCOME DIALOG */
    WELCOME_DIALOG_TITLE,
    WELCOME_RECENT_WORK,
    WELCOME_CREATE_NEW,
    WELCOME_NAME_TITLE,
    WELCOME_NAME_PROMPT,
    WELCOME_NEW_ICON,
    WELCOME_RECENT_ICON,
    WELCOME_RECENT_EMPTY,
    WELCOME_RECENT_EMPTY_ICON,

    /* Metro Lines Toolbar */
    METRO_LINES_LABEL,
    METRO_LINES_ADD_TOOLTIP,
    METRO_LINES_DELETE_TOOLTIP,
    METRO_LINES_ADD_STATION,
    METRO_LINES_ADD_STATION_TOOLTIP,
    METRO_LINES_REMOVE_STATION,
    METRO_LINES_REMOVE_STATION_TOOLTIP,
    METRO_LINES_LIST_STATIONS_TOOLTIP,
    METRO_LINES_EDIT_TOOLTIP,

    /* Metro Station Toolbar */
    METRO_STATIONS_LABEL,
    METRO_STATIONS_ADD_TOOLTIP,
    METRO_STATIONS_DELETE_TOOLTIP,
    METRO_STATIONS_SNAP,
    METRO_STATIONS_SNAP_TOOLTIP,
    METRO_STATIONS_MOVE_LABEL,
    METRO_STATIONS_MOVE_LABEL_TOOLTIP,
    METRO_STATIONS_ROTATE_LABEL,

    /* Directions Toolbar */
    METRO_DIRECTIONS_BUTTON_TOOLTIP,

    /* Decor Toolbar */
    METRO_DECOR_LABEL,
    METRO_DECOR_SET_IMAGE_BG,
    METRO_DECOR_SET_IMAGE_BG_TOOLTIP,
    METRO_DECOR_ADD_IMAGE,
    METRO_DECOR_ADD_IMAGE_TOOLTIP,
    METRO_DECOR_ADD_LABEL,
    METRO_DECOR_ADD_LABEL_TOOLTIP,
    METRO_REMOVE_ELEMENT,
    METRO_REMOVE_ELEMENT_TOOLTIP,

    /* Font Toolbar */
    METRO_FONT_LABEL,
    METRO_FONT_BOLD_TOOLTIP,
    METRO_FONT_ITALICS_TOOLTIP,

    /* Navigation Toolbar */
    METRO_NAV_LABEL,
    METRO_NAV_ZOOM_IN_TOOLTIP,
    METRO_NAV_ZOOM_OUT_TOOLTIP,
    METRO_NAV_SCALE_DOWN_TOOLTIP,
    METRO_NAV_SCALE_UP_TOOLTIP,
    METRO_NAV_GRID_CHECK,

    /* EDIT LINE DIALOG */
    EDIT_LINE_TITLE,
    EDIT_LINE_LABEL,

    /* LIST STOPS DIALOG */
    STOPS_TITLE,
    STOPS_LABEL,

    /* ROUTE DIALOG */
    ROUTE_TITLE,
    ROUTE_LABEL,

    /* ABOUT DIALOG */
    ABOUT_TOOLTIP,
    APP_TITLE,
    APP_LOGO,
    ABOUT_CREDITS,
    ABOUT_COPYRIGHT,

    /* COMBOBOX OPTIONS */
    FONT_FAMILY_COMBO_BOX_OPTIONS,
    FONT_SIZE_COMBO_BOX_OPTIONS
}
